services:
  - type: web
    name: moses-portfolio
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --no-input
    startCommand: gunicorn portfolio.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "moses-portfolio.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://moses-portfolio.onrender.com"
